src/RecepieBank/Models/Enums/Units.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecepieBank.Models.Enums
{
    public enum Units
    {
        ml,
        cl,
        dl,
        l,
        g,
        hg,
        kg,
        krm,
        tsk,
        msk,
        st
    }
}

src/RecepieBank/Models/Ingredient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecepieBank.Models
{
    public class Ingredient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<IngredientInRecepie> Recepies { get; set; }
    }
}

src/RecepieBank/Models/IngredientInRecepie.cs
using RecepieBank.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecepieBank.Models
{
    public class IngredientInRecepie
    {
        public int Id { get; set; }
        public float? Quantity { get; set; }
        public Units Unit { get; set; }
        public int IngredientId { get; set; }
        public Ingredient Ingredient { get; set; }
        public int RecepieId { get; set; }
        public Recepie Recepie { get; set; }
    }
}

src/RecepieBank/Models/Recepie.cs
using RecepieBank.Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RecepieBank.ViewModels;

namespace RecepieBank.Models
{
    public class Recepie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EstimatedTime { get; set; }
        public int? OvenTemperature { get; set; }
        public ICollection<IngredientInRecepie> Ingredients { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
    }
}

src/RecepieBank/ViewModels/IngredientInRecepieVM.cs
using RecepieBank.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecepieBank.ViewModels
{
    public class IngredientInRecepieVM
    {
        public int IngredinetId { get; set; }
        public string IngredientName { get; set; }
        public Units Unit { get; set; }
        public float? Quantity { get; set; }
        public int RecepieId { get; set; }
    }
}

src/RecepieBank/ViewModels/IngredientVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecepieBank.ViewModels
{
    public class IngredientVM
    {
        public int IngredientId { get; set; }
        public string Name { get; set; }
    }
}

src/RecepieBank/ViewModels/NewIngredientInRecepieVM.cs
using RecepieBank.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecepieBank.ViewModels
{
    public class NewIngredientInRecepieVM
    {
        public int RecepieId { get; set; }
        public int IngredientId { get; set; }
        public Units Unit { get; set; }
        public float? Quantity { get; set; }
        public ICollection<IngredientVM> Ingredients { get; set; }
    }
}

src/RecepieBank/ViewModels/RecepieVM.cs
using RecepieBank.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecepieBank.ViewModels
{
    public class RecepieVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EstimatedTime { get; set; }
        public int? OvenTemparature { get; set; }
        public ICollection<IngredientInRecepieVM> Ingredients { get; set; }
        public ICollection<string> Description{ get; set; }
    }
}

src/RecepieBank/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RecepieBank.ViewModels;
using RecepieBank.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace RecepieBank.Controllers
{
    public class IngredientController : Controller
    {
        private IIngredientReopsitory ingredientRepository;

        public IngredientController(IIngredientReopsitory ingredientRepository)
        {
            this.ingredientRepository = ingredientRepository;
        }
        // GET: /<controller>/
        //[Route("ingredient/addIngredient/{recepieId:int}")]
        public IActionResult AddIngredient(List<IngredientInRecepieVM> recepie)
        {
            recepie.Add(new IngredientInRecepieVM());
            return View(recepie);
        }

        //[HttpPost]
        //public IActionResult AddIngredient(RecepieVM model)
        //{
        //    return RedirectToAction(nameof(RecepieController.Recepies), "Recepie");
        //}
    }
}

src/RecepieBank/Controllers/RecepieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RecepieBank.Repositories.Interfaces;
using RecepieBank.ViewModels;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace RecepieBank.Controllers
{
    public class RecepieController : Controller
    {
        private IRecepieRepository recepieRepository;

        public RecepieController(IRecepieRepository recepieRepository)
        {
            this.recepieRepository = recepieRepository;
        }

        // GET: /<controller>/
        public IActionResult Recepies()
        {
            return View(recepieRepository.Recepies());
        }

        public IActionResult NewRecepie()
        {
            return View(recepieRepository.NewRecepie());
        }

        [HttpPost]
        public IActionResult NewRecepie(RecepieVM model)
        {
            
            return RedirectToAction(nameof(RecepieController.Recepies));
        }

        public IActionResult Recepie(int id)
        {
            var model = recepieRepository.RecepieById(id);
            return View(model);
        }

        public IActionResult DeleteRecepie(int id)
        {
            recepieRepository.DeleteRecepieById(id);
            return RedirectToAction(nameof(RecepieController.Recepies));
        }
    }
}

src/RecepieBank/Views/Ingredient/AddIngredient.cshtml
@model List<IngredientInRecepieVM>
<form asp-controller="ingredient" asp-action="AddIngredient">
    <input asp-for="@Model.Last().Quantity" />
    <select asp-for="@Model.Last().IngredinetId" asp-items="@(new SelectList(Model.Last().Ingredients, "IngredientId","Name"))">
    </select>
    <input type="submit" value="Add to recepie" />
</form>

src/RecepieBank/Views/Recepie/NewRecepie.cshtml
@model RecepieVM

<form asp-controller="Recepie" asp-action="AddRecepie">
    <input type="hidden" value="@Model.Id" />
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <label asp-for="Ingredients"></label>
    <a asp-controller="ingredient" asp-action="addIngredient" asp-route-recepie="@Model.Ingredients">Add</a>
    <ul>
        @foreach (var item in Model.Ingredients)
        {
            <li>
                @item.Quantity @item.Unit
            </li>
        }
    </ul>
    <input type="submit" value="Save" />
</form>

src/RecepieBank/Views/Recepie/Recepie.cshtml
@model RecepieVM
@{ 
    ViewBag.Title = Model.Name;
}

<a asp-controller="Recepie" asp-action="DeleteRecepie" asp-route-id="@Model.Id">Delete</a>

<ul>
    @foreach (var item in Model.Ingredients)
    {
        <li>@item.Quantity @item.Unit @item.IngredientName</li>
    }
</ul>

<ol>
    @foreach (var item in Model.Description)
    {
        <li>@item</li>
    }
</ol>

src/RecepieBank/Views/Recepie/Recepies.cshtml
@model RecepieVM[]
<a asp-controller="Recepie" asp-action="NewRecepie">New recepie</a>
<ul>
    @foreach (var recepie in Model)
    {
        <li>
            <a href="recepie/@recepie.Id">@recepie.Name</a>
        </li>
    }
</ul>

src/RecepieBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>